Restoring original file, produces this error:
TypeError: Cannot set property rendererType of class BaseComponent {
    static get rendererType() {
        return this.componentType;
    }
    get componen...<omitted>...
} which has only a getter